// <auto-generated />
using System;
using Gmax.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gmax.Migrations
{
    [DbContext(typeof(GmaxDbContext))]
    [Migration("20241204183614_RegenerateDbForPostgreSQL")]
    partial class RegenerateDbForPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gmax.Models.Entities.ArticoloCK", b =>
                {
                    b.Property<string>("TipoArticolo")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CodiceArticolo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CodCostruttore")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CodUbicazione")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("DataInserimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("QtaImpCliente")
                        .HasColumnType("integer");

                    b.Property<decimal?>("QtaScortaMin")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<string>("UnitaMisuraGestione")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("TipoArticolo", "CodiceArticolo");

                    b.ToTable("ArticoliCK");
                });

            modelBuilder.Entity("Gmax.Models.Entities.AssegnazioneMagazzino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("DataAssegnazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<int>("NroLancio")
                        .HasColumnType("integer");

                    b.Property<int>("NroSottolancio")
                        .HasColumnType("integer");

                    b.Property<int>("Quantita")
                        .HasColumnType("integer");

                    b.Property<int>("SorgenteAssegnazione")
                        .HasColumnType("integer");

                    b.Property<string>("TipoArticolo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("NroLancio", "NroSottolancio", "TipoArticolo", "CodiceArticolo");

                    b.ToTable("AssegnazioniMagazzino");
                });

            modelBuilder.Entity("Gmax.Models.Entities.OrdineProdCompCK", b =>
                {
                    b.Property<int>("NroLancio")
                        .HasColumnType("integer");

                    b.Property<int>("NroSottolancio")
                        .HasColumnType("integer");

                    b.Property<string>("TipoArticolo")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CodiceArticolo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("QtaGiaScaricata")
                        .HasPrecision(14, 4)
                        .HasColumnType("integer");

                    b.Property<decimal>("QtaPrevista")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<int>("SeqArt")
                        .HasColumnType("integer");

                    b.Property<int>("SeqOp")
                        .HasColumnType("integer");

                    b.HasKey("NroLancio", "NroSottolancio", "TipoArticolo", "CodiceArticolo");

                    b.HasIndex("TipoArticolo", "CodiceArticolo");

                    b.ToTable("OrdiniProdCompCK");
                });

            modelBuilder.Entity("Gmax.Models.Entities.OrdineProduzioneCK", b =>
                {
                    b.Property<int>("NroLancio")
                        .HasColumnType("integer");

                    b.Property<int>("NroSottolancio")
                        .HasColumnType("integer");

                    b.Property<string>("CodArtLancio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPrevCons")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("TipoArtLancio")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("NroLancio", "NroSottolancio");

                    b.HasIndex("TipoArtLancio", "CodArtLancio");

                    b.ToTable("OrdiniProduzioneCK");
                });

            modelBuilder.Entity("Gmax.Models.Entities.AssegnazioneMagazzino", b =>
                {
                    b.HasOne("Gmax.Models.Entities.OrdineProdCompCK", "OrdineProdCompCK")
                        .WithMany("Assegnazioni")
                        .HasForeignKey("NroLancio", "NroSottolancio", "TipoArticolo", "CodiceArticolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdineProdCompCK");
                });

            modelBuilder.Entity("Gmax.Models.Entities.OrdineProdCompCK", b =>
                {
                    b.HasOne("Gmax.Models.Entities.OrdineProduzioneCK", "OrdineProduzioneCK")
                        .WithMany("OrdineProdCompCKList")
                        .HasForeignKey("NroLancio", "NroSottolancio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gmax.Models.Entities.ArticoloCK", "Articolo")
                        .WithMany("OrdineProdCompCKList")
                        .HasForeignKey("TipoArticolo", "CodiceArticolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");

                    b.Navigation("OrdineProduzioneCK");
                });

            modelBuilder.Entity("Gmax.Models.Entities.OrdineProduzioneCK", b =>
                {
                    b.HasOne("Gmax.Models.Entities.ArticoloCK", "ArtLancio")
                        .WithMany("OrdineProduzioneLancioList")
                        .HasForeignKey("TipoArtLancio", "CodArtLancio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtLancio");
                });

            modelBuilder.Entity("Gmax.Models.Entities.ArticoloCK", b =>
                {
                    b.Navigation("OrdineProdCompCKList");

                    b.Navigation("OrdineProduzioneLancioList");
                });

            modelBuilder.Entity("Gmax.Models.Entities.OrdineProdCompCK", b =>
                {
                    b.Navigation("Assegnazioni");
                });

            modelBuilder.Entity("Gmax.Models.Entities.OrdineProduzioneCK", b =>
                {
                    b.Navigation("OrdineProdCompCKList");
                });
#pragma warning restore 612, 618
        }
    }
}
