// <auto-generated />
using System;
using Gmax.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Gmax.Migrations
{
    [DbContext(typeof(GmaxDbContext))]
    [Migration("20241013213958_ColonnaCostruttoreAdArticolo")]
    partial class ColonnaCostruttoreAdArticolo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gmax.Models.Entities.Articolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodCostruttore")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("CodUbicazione")
                        .HasMaxLength(6)
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<DateTime?>("DataInserimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<int?>("QtaImpCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("QtaScortaMin")
                        .HasPrecision(14, 4)
                        .HasColumnType("DECIMAL(14,4)");

                    b.Property<string>("TipoArticolo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)");

                    b.Property<string>("UnitaMisuraGestione")
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)");

                    b.HasKey("Id");

                    b.HasIndex("TipoArticolo", "CodiceArticolo")
                        .IsUnique();

                    b.ToTable("Articoli");
                });
#pragma warning restore 612, 618
        }
    }
}
