// <auto-generated />
using Gmax.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Gmax.Migrations
{
    [DbContext(typeof(GmaxDbContext))]
    [Migration("20241011091540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gmax.Models.Entities.Articolo", b =>
                {
                    b.Property<string>("CodiceArticolo")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("TipoArticolo")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QtaImpCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QtaScortaMin")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("UnitaMisura")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CodiceArticolo", "TipoArticolo");

                    b.ToTable("Articoli");
                });
#pragma warning restore 612, 618
        }
    }
}
